### ISSUE TITLE
Example fails because of API schema issue

### ISSUE THREAD

**Issue by volatilemolotov** [moonbeam-nyc/snorlax#5]
When trying out the example from github it fails with

Error from server (BadRequest): error when creating "infra/ollama/ollama-sleep-shedule.yaml": SleepSchedule in version "v1beta1" cannot be handled as a SleepSchedule: strict decoding error: unknown field "spec.ingresses[0].requires.deployments"

Commenting out the requires from ingresses helps:

```
  ingresses:
  - name: openweb-ui

    # (optional, defaults to all deployments) specify which deployments
    # must be ready to wake this ingress
    # requires:
    #   deployments:
    #   - name: test
```

**Comment by azlyth** [comment]
Nooo, sorry @volatilemolotov, the README example was wrong, I've updated it now, the correct format is:

```
    # (optional, defaults to all deployments) specify which deployments
    # must be ready to wake this ingress
    requires:
    - deployment:
        name: your-app-frontend
```
